#!/bin/bash
condor_submit submit_files/submit_2024_vsjet_VVLoose_vse_VVLoose.sub
condor_submit submit_files/submit_2024_vsjet_VVLoose_vse_Tight.sub
condor_submit submit_files/submit_2024_vsjet_VLoose_vse_VVLoose.sub
condor_submit submit_files/submit_2024_vsjet_VLoose_vse_Tight.sub
condor_submit submit_files/submit_2024_vsjet_Loose_vse_VVLoose.sub
condor_submit submit_files/submit_2024_vsjet_Loose_vse_Tight.sub
condor_submit submit_files/submit_2024_vsjet_Medium_vse_VVLoose.sub
condor_submit submit_files/submit_2024_vsjet_Medium_vse_Tight.sub
condor_submit submit_files/submit_2024_vsjet_Tight_vse_VVLoose.sub
condor_submit submit_files/submit_2024_vsjet_Tight_vse_Tight.sub
condor_submit submit_files/submit_2024_vsjet_VTight_vse_VVLoose.sub
condor_submit submit_files/submit_2024_vsjet_VTight_vse_Tight.sub
