## Config file for default TES fit in mutau channel
##

channel: mumu

#tag: "_mumu"
tag: "_mumu" # tag used for derivation of TauES SFs for 2022_preEE and 2022_postEE


baselineCuts: "q_1*q_2<0 && iso_1<0.15 && iso_2<0.15 && !lepton_vetoes && metfilter"


samples:
    filename: "$PICODIR/$SAMPLE_$CHANNEL$TAG.root"
    join: ["VV","TT","ST"]
    split:
        DY: [ ["ZTT","genmatch_2==5"], ["ZL","genmatch_2>0 && genmatch_2<5"], ["ZJ","genmatch_2==0"] ]
    #     TT: [["TTT","genmatch_2==5"], ["TTL","genmatch_2>0 && genmatch_2<5"], ["TTJ","genmatch_2==0"] ]
    rename:
        WJ: "W"
        DY: "ZLL"
        TT: "TT"
    data: "data_obs"
    removeSFs: []

observables:
    m_vis:
        binning: [1, 40, 150]
        extra:
            ymargin: 1.6
            rrange: 0.20
        fitRegions: ["baseline"]

processes: ['ZL', 'ZTT', 'ZJ', 'W','VV','ST', 'TT','QCD','data_obs'] #['ZTT','ZL', 'ZJ','W','VV','ST','TTT', 'TTL', 'TTJ','QCD','data_obs'] #'ZTT','ZL','ZJ','data_obs'] 

systematics:
    xsec_dy:
        effect: "lnN"
        processes: ["ZTT", "ZL", "ZJ"]
        scaleFactor: 1.02
    # lumi:
        # effect: "lnN"
        # processes: ['ZL', 'ZTT', 'ZJ']
        # scaleFactor: 1.025
    # eff_m:
        # effect: "lnN"
        # processes: ["ZL", "ZTT", "ZJ"]
        # scaleFactor: 1.02
    # xsec_tt:
        # effect: "lnN"
        # processes: ["TT"]
        # scaleFactor: 1.06
    # xsec_st:
        # effect: "lnN"
        # processes: ["ST"]
        # scaleFactor: 1.05
    # norm_wj:
        # effect: "lnN"
        # processes: ["W"]
        # scaleFactor: 1.08
